### ISSUE TITLE
Add Vanilo 4.x support

### ISSUE THREAD

**Issue by xujiongze** [vanilophp/braintree#3]
Add Vanilo 4.x support

**Comment by fulopattila122** [comment]
Vanilo 4 just got released a few hours ago, and we're working on bringing all the modules, documentation, etc to pair with the 4.x series

**Comment by xujiongze** [comment]
@fulopattila122 Thanks for your hard work

**Comment by xujiongze** [comment]
@fulopattila122 Missing implement Vanilo\Payment\Contracts\PaymentRequest::getRemoteId

**Comment by fulopattila122** [comment]
> @fulopattila122 Missing implement Vanilo\Payment\Contracts\PaymentRequest::getRemoteId

my bad :see_no_evil:  - please upgrade the package to v2.0.1
