### ISSUE TITLE
Missing to implement: Vanilo\Payment\Contracts\PaymentResponse::getTransactionAmount

### ISSUE THREAD

**Issue by xujiongze** [vanilophp/braintree#4]
Sorry for say one by one, but today, I found this error.

Class Vanilo\Braintree\Messages\BraintreePaymentResponse contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Vanilo\Payment\Contracts\PaymentResponse::getTransactionAmount)

**Comment by fulopattila122** [comment]
No worries, thanks for taking care of this module!

**Comment by fulopattila122** [comment]
Fix released as v2.0.2
